apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

  #vpc:
  #id: "vpc-05cadda085d890b4c"  # (optional, must match VPC ID used for each subnet below)
  #cidr: "10.0.0.0/21"       # (optional, must match CIDR used by the given VPC)
  #subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    #  private:
    #  us-east-1a:
    #    id: "subnet-0207cda7d5ee79c80"
    #    cidr: "10.0.4.0/24" # (optional, must match CIDR used by the given subnet)

  #  us-east-1b:
  #      id: "subnet-02d0d563e7b4c6861"
  #      cidr: "10.0.5.0/24"  # (optional, must match CIDR used by the given subnet)

  #   us-east-1c:
  #      id: "subnet-0fa7079f2e1cf54d4"
  #      cidr: "10.0.6.0/24"   # (optional, must match CIDR used by the given subnet)


nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
